env:
  base_url: "http://172.17.0.1:8080"

generation_config:
  num_of_tests: 40
  num_of_apis: 5
  control_position_candidate: [3, 4] # When idx == 4, it means no control flow.
  trace_config:
    init_local_state_num_range: [2, 3]
    init_implicit_state_num_range: [3, 6]
  
