task: "session"
env:
  base_url: "http://172.17.0.1:8080"
  trace_save_path: "/data/huangyuheng/stateful_bench/session_trace"
  agent_save_path: "/data/huangyuheng/stateful_bench/session_trace/agent_data"
  api_key: "REDACTED_API_KEY"

generation_config:
  num_of_tests: 60
  num_of_apis: 5
  control_position_candidate: [3, 4] # When idx == 4, it means no control flow.
  trace_config:
    init_local_state_num_range: [2, 3]
    init_implicit_state_num_range: [3, 6]

agent_config:
  max_iterations: 3
  
